export const AUTH_START = 'AUTH_START'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGOUT = 'LOGOUT'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_SOCKET = "SET_SOCKET";
export const REMOVE_SOCKET = "REMOVE_SOCKET";

export const GET_ROOMS_START = 'GET_ROOMS_START'
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS'
export const GET_ROOMS_FAILURE = 'GET_ROOMS_FAILURE'
export const ADD_ROOM = 'ADD_ROOM'
export const SELECT_ROOM = "SELECT_ROOM"
export const ADD_MESSAGE = "ADD_MESSAGE"  //ADDING MESSAGE TO SELECTED ROOM ONLY
export const UPDATE_MESSAGE_COUNT = "UPDATE_MESSAGE_COUNT"
export const ADD_MESSAGE_TO_ROOM = "ADD_MESSAGE_TO_ROOM"
export const REMOVE_SELECTED_ROOM = "REMOVE_SELECTED_ROOM"
export const MARK_READ_IN_SELECTED_ROOM = 'MARK_READ_IN_SELECTED_ROOM'   //when both users ae in the room
export const MARK_READ_IN_ROOM = 'MARK_READ_IN_ROOM'